spring:
  datasource:
    url: jdbc:mysql://localhost/gymapp
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
server:
  port: 8080
  servlet:
    session:
      timeout: 600